# Generated by Django 4.0.5 on 2022-07-04 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoBackendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='ending',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 10, 43, 53, 848356), max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=2129039956, editable=False, max_length=10, unique=True, verbose_name='meeting id'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starting',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 10, 13, 53, 848356), max_length=200),
        ),
    ]
