# Generated by Django 4.0.5 on 2022-07-04 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoBackendApp', '0002_alter_meeting_ending_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'permissions': [('can_start_meeting', 'can start a meeting'), ('can_join_meeting', 'can join a meeting')]},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='ending',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 13, 3, 22, 339615), max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=3745771940, editable=False, max_length=10, unique=True, verbose_name='meeting id'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starting',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 12, 33, 22, 339615), max_length=200),
        ),
    ]
