# Generated by Django 4.0.5 on 2022-07-03 17:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('VideoBackendApp', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('title', models.CharField(max_length=700, verbose_name="meeting's title")),
                ('id', models.BigIntegerField(default=range(0, 22), primary_key=True, serialize=False, unique=True, verbose_name='meeting id')),
                ('password', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
                ('starting', models.DateTimeField(default=datetime.datetime(2022, 7, 3, 18, 47, 55, 717904), max_length=100)),
                ('ending', models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 17, 55, 717904), max_length=200)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
