# Generated by Django 4.0.5 on 2022-07-03 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoBackendApp', '0003_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='ending',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 19, 22, 919448), max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.BigIntegerField(default=range(0, 21), primary_key=True, serialize=False, unique=True, verbose_name='meeting id'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starting',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 18, 49, 22, 919448), max_length=200),
        ),
    ]
