# Generated by Django 4.0.5 on 2022-07-15 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoBackendApp', '0004_alter_meeting_ending_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='id',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='ending',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 7, 22, 12, 223480), max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=9249299292, editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='meeting id'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starting',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 6, 52, 12, 223480), max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures/', verbose_name='Profile Image'),
        ),
    ]
