# Generated by Django 4.0.5 on 2022-07-15 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoBackendApp', '0005_remove_meeting_id_alter_meeting_ending_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'permissions': [('can_start_meeting', 'can start a meeting'), ('can_join_meeting', 'can join a meeting'), ('can_delete_meeting', 'can delete meeting')]},
        ),
        migrations.AddField(
            model_name='meeting',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='ending',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 22, 1, 41, 397556), max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=4580964814, editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='meeting id'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starting',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 21, 31, 41, 397556), max_length=200),
        ),
    ]
