# Generated by Django 4.0.5 on 2022-07-24 14:35

import VideoBackendApp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoBackendApp', '0011_alter_meeting_ending_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='ending',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 16, 5, 44, 684248), max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=VideoBackendApp.models.Meeting.generate_random_id, editable=False, max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='meeting id'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starting',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 15, 35, 44, 684248), max_length=200),
        ),
    ]
